---

- name: Restart Jenkins service
  service:
    name: "{{ jenkins_master_service }}"
    state: restarted
  when: >
    jenkins_master_service_started is not defined or
    not jenkins_master_service_started.changed
